- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add UNetbootin Repository
    apt_repository:
      repo: ppa:gezakovacs/ppa
      tags:
        - unetbootin
      become: true

  - name: Install Ubuntu packages
    apt: name={{item}} state=present
    with_items:
    - tree
    - httpie
    # https://httpie.org/
    - tldr
    - python
    - python-pip
    - python3
    - python3-pip
    - file-roller
    - audacity
    - bleachbit
    - dconf-editor
    - baobab
    - gnome-font-viewer
    - gnome-disk-utility
    - gnome-system-monitor
    - gnome-power-manager
    - gnome-tweak-tool
    - gdebi-core
    - gparted
    - menulibre
    - pinta
      # to configure custom icons' dock
    - plank
    - pulseaudio
    - remmina
    - transmission
    - vlc
    - unetbootin
    become: true


  - name: Configure plank
    user:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
    loop:
      - { name: "/net/launchpad/plank/dock/settings/icon-size", value: "48" }
      - { name: "/net/launchpad/plank/dock/settings/show-dock-item", value: "false" }
      - { name: "/net/launchpad/plank/dock/settings/position", value: "bottom" }
      - { name: "/net/launchpad/plank/dock/settings/unhide-delay", value: "0" }
      - { name: "/net/launchpad/plank/dock/settings/items-alignment", value: "center" }
      - { name: "/net/launchpad/plank/dock/settings/theme", value: "Gtk+" }
      - { name: "/net/launchpad/plank/dock/settings/hide-mode", value: "window-dodge" }
      - { name: "/net/launchpad/plank/dock/settings/pinned-only", value: "false" }
      - { name: "/net/launchpad/plank/dock/settings/auto-pinning", value: "true" }
      - { name: "/net/launchpad/plank/dock/settings/alignment", value: "center" }
      - { name: "/net/launchpad/plank/dock/settings/zoom-percent", value: "150" }
      - { name: "/net/launchpad/plank/dock/settings/hide-delay", value: "250" }
      - { name: "/net/launchpad/plank/dock/settings/zoom-enabled", value: "false" }
      - { name: "/net/launchpad/plank/dock/settings/monitor", value: "" }
      - { name: "/net/launchpad/plank/dock/settings/lock-items", value: "false" }
      - { name: "/net/launchpad/plank/dock/settings/tooltips-enabled", value: "true" }
      - { name: "/net/launchpad/plank/dock/settings/pressure-reveal", value: "false" }
      - { name: "/net/launchpad/plank/dock/settings/offset", value: "0" }
      - { name: "/net/launchpad/plank/dock/settings/current-workspace-only", value: "false" }