FROM ubuntu:bionic

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common systemd aptitude && rm -rf /var/lib/apt/lists/*

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && DEBIAN_FRONTEND=noninteractive aptitude install -y -q \
    ansible \
    apt-transport-https \
    apt-utils \
    arj \
    audacity \
    baobab \
    bleachbit \
    build-essential \
    ca-certificates \
    cabextract \
    cmake \
    curl \
    dconf-cli \
    dconf-editor \
    ffmpeg \
    file-roller \
    fontconfig \
    gdebi-core \
    git \
    git-core \
    gnome-disk-utility \
    gnome-font-viewer \
    gnome-power-manager \
    gnome-system-monitor \
    gnome-tweak-tool \
    gparted \
    httpie \
    libavcodec-extra \
    libcap2-bin \
    libdvd-pkg \
    libinput-tools \
    lunzip \
    lzip \
    menulibre \
    mpack \
    openjdk-11-jdk \
    openjdk-11-jre \
    p7zip \
    p7zip-rar \
    pinta \
    powerline \
    pulseaudio \
    python \
    python-pip \
    python-psutil \
    python3 \
    python3-pip \
    python3-psutil \
    rar \
    remmina \
    yakuake \
    ruby \
    rsync \
    screen \
    sharutils \
    shutter \
    snapd \
    software-properties-common \
    tldr \
    transmission \
    tree \
    unace \
    unrar \
    uudeview \
    variety \
    vim \
    vlc \
    wget \
    wireshark \
    xdotool \
    zlib1g-dev \
    zsh \
 && rm -rf /var/lib/apt/lists/* \
 && ansible-galaxy install bendews.cloudflared \
 && { echo '[defaults]'; \
      echo 'gathering = smart'; \
      echo 'fact_caching = jsonfile'; \
      echo 'fact_caching_connection = /tmp/facts_cache'; \
      echo 'fact_caching_timeout = 7200'; \
      echo 'callback_whitelist = profile_tasks'; \
      } >> ansible.cfg


RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
